# Generated by Django 5.2.5 on 2025-09-30 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
